site_name: SIISLtd.Migrations docs
site_url: https://siisltdmigrations.rtfd.io
site_description: Curiosity.Migrations
site_author: SIIS Ltd
copyright: SIIS Ltd © 2020

nav:
  - 'Intro' : 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'Usage': 'usage.md'
  - 'Features': 'features.md'
      - 'Script Migration' : 'features/script_migration.md'
      - 'Code Migration' : 'features/code_migration.md'
      - 'EntityFramework Integration' : 'features/ef_integration.md'
      - 'Migration Providers' : 'features/script_providers.md'
      - 'Variables' : 'features/variables.md'
      - 'Transactions' : 'features/transactions.md'
      - 'Pre-migrations' : 'features/pre_migrations.md'
      - 'Journal' : 'features/journal.md'

#theme: readthedocs


theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'red'
    accent: 'red'

markdown_extensions:
  - codehilite
  - markdown_include.include:
      base_path: docs

